### PR TITLE
Fixed a bug which occured with 'Null' days.

### PR DESCRIPTION
**Pull request by gohara92**
Fixed a minor bug that was occuring when installing.
With a schedule block where the weekday was Null, the loop in Schedule.is_active() would sometimes incorrectly return 'False' on days that weren't Monday.
This was due to the second nested return statement:
     - Since the weekday is Null, the loop steps through range(1,8).
     - The loop would reach yesterday, and enter into its second if block.
     - If the schedule block was with one day (eg from 9am to 5pm), then duration.days == 0, so that 'False' would be returned, even if the current time was e.g 11am.
     - However, if the loop had the opportunity to continue onto the next working day, it would enter the first if statement and have the opportunity to properly test whether it should return True.

I fixed this by removing the return statement, and replacing it with a boolean variable to be updated rather than returned immediately. This stops the loop ending prematurely.

There are probably more elegant ways to do this, but I thought this was quite simple.

### CODE REVIEW

**Comment by cmnord** [comment]
Thank you for the PR! I refactored things a bit and added tests to catch the bug in #2.

**Comment by gohara92** [comment]
Great, thanks!
Unfortunately I had to switch back to the earlier (sbibauw's) branch in the end as I couldn't get this one working - I thought it might be something to do with the com.parrot-bytes.auto-selfcontrol.plist file calling the Python script with an "-r" flag, so I did do a bit of experimentation but still didn't have any luck.
If that is actually what the problem is, I could take a bit more a look.

**Comment by cmnord** [comment]
Oh hmm, what was the specific error?

**Comment by gohara92** [comment]
So I'd installed it successfully, and it started SelfControl for the block
I was in - but didn't start it for the block after.
This was what led me to think it might be something with the daemon, but I
checked that with `launchctl` and it was loaded correctly etc.

**Comment by cmnord** [comment]
Hmm, I think I encountered this problem as well 🤨 I'll check that my launchscript `.plist` file is the exact same as sbibauw's.

**Comment by gohara92** [comment]
If you had this as well (so it's not just my system) I think the
launchscript being the same is what causes the problem - it calls the
Python script with a "-r" flag/argument, and I don't think there's handling
for a "-r" flag in the script.
I'll try to look into it this weekend!

**Comment by cmnord** [comment]
Ohh! I see now, with the diff [here](https://github.com/sbibauw/auto-selfcontrol/blob/master/auto-selfcontrol.py#L265).

**Comment by cmnord** [comment]
This is what happens when the command line interface is split across a bash script and a python script 😛

**Comment by cmnord** [comment]
I'll test #3 tomorrow

**Comment by gohara92** [comment]
Great stuff!

**Pull request closed without merging**
